<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Excercise 1

| # | Term       | Description                                                                                                                                                                                           |
|---|------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1 | Subsetting | Selecting certain elements from an iterable object. |
| 2 | Indexing   | Using indices to access an element in an iterable object.                                                                                                                               |
| 3 | Slicing    | Using specific notation to specify a start and end value in order to obtain a specific section of an iterable object.|
| 4 | Masking    | A subsetting proceedure whereby we apply a given predicate to all values in a numpy array and get a boolean output.                                                                                                                              |


# Excercise 2

In [15]:
import numpy
np_array_2d = numpy.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
newarray=np_array_2d[:,0].astype(int)
mask=newarray%2==1
print(np_array_2d[mask][:,1])

['A' 'C' 'E' 'G' 'I']


# Excercise 3

In [16]:
import numpy
array1=numpy.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
mask1a=array1<50
mask2=array1>50
mask1=mask1a*-1
array_final=mask1+mask2
print(array_final)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
